import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    padding: 25,
    flex: 1,
    backgroundColor: "#1F1F1F",
    // alignItems: "center",
    flexDirection: "column",
    width: "100%",
  },
  column: {
    flex: 1,
    flexDirection: "column",
  },
  row: {
    flex: 1,
    flexDirection: "row",
  },
  counter: {
    fontSize: 18,
    fontWeight: "bold",
    width: 30,
    height: 30,
    borderRadius: 15,
    borderColor: "#FFE600",
    borderWidth: 3,
    backgroundColor: "#1F1F1F",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 15,
    marginBottom: 15,
  },
  counterText: {
    color: "#FFE600",
    fontWeight: "bold",
    fontFamily: "Azeret",
  },
  title: {
    width: 300,
    textAlign: "left",
    fontSize: 32,
    fontWeight: "bold",
  },
  profile: {
    marginTop: 50,
    width: 150,
    height: 150,
    resizeMode: "stretch",
  },
  buttonContainer: {
    marginTop: 50,
    backgroundColor: "#cccccc",
    borderRadius: 40,
    width: 100,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: {
      width: 5,
      height: 4,
    },
  },
  heading: {
    fontSize: 18,
    fontWeight: "bold",
    color: "white",
    fontFamily: "Azeret",
    marginTop: 4,
  },
  fact: {
    fontSize: 18,
    marginTop: 16,
    shadowOpacity: 0,
  },
  facts: {
    backgroundColor: "#ededed",
    borderRadius: 10,
    paddingTop: 0,
    paddingLeft: 16,
    paddingRight: 16,
    paddingBottom: 16,
    width: "100%",
    textAlign: "left",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: {
      width: 5,
      height: 4,
    },
  },
});
